#%RAML 1.0 NamedExample
value:
  -
    book:
      isbn: "978-1-2345-6789-0"
      title: "My interesting life"
      genre: "Biography"
      currency: "euro"
      price: 9.99
      review: "Very, very good"
      publishingDate: 2019-01-01
    writers:
      -
        writer:
          author: "John Doe"
        address:
          buildingHouseNumber: "123"
          streetName: "StreetName1"
          cityName: "CityName1"
          stateProvince: "StateProvince1"
          postalCode: "12345"
    publishers:
      -
        publisher:
          id: 1
          publisherName: "PublishersName11"
        address: 
          poBoxNumber: "12345"
          buildingHouseNumber: "231"
          streetName: "StreetName11"
          cityName: "CityName11"
          stateProvince: "StateProvince11"
          postalCode: "11345"
        regions: 
          - region: "Africa"
          - region: "Europe"
      -
        publisher:
          id: 2
          publisherName: "PublishersName12"
        address: 
          poBoxNumber: "23451"
          buildingHouseNumber: "312"
          streetName: "StreetName12"
          cityName: "CityName12"
          stateProvince: "StateProvince12"
          postalCode: "12345"
        regions: 
          - region: "Asia"
  -
    book:
      isbn: "978-2-3456-7890-1"
      title: "My favorite destinations"
      genre: "Travel"
      currency: "euro"
      price: 19.99
      review: "Very, very interesting"
      publishingDate: 2019-02-02
    writers:
      -
        writer:
          author: "Jane Whats Her Name"
        address:
          buildingHouseNumber: "456"
          streetName: "StreetName2"
          cityName: "CityName2"
          stateProvince: "StateProvince2"
          postalCode: "23456"
    publishers:
      -
        publisher:
          id: 1
          publisherName: "PublishersName21"
        address: 
          poBoxNumber: "23451"
          buildingHouseNumber: "456"
          streetName: "StreetName21"
          cityName: "CityName21"
          stateProvince: "StateProvince21"
          postalCode: "22345"
        regions: 
          - region: "America"
          - region: "Europe"
      -
        publisher:
          id: 2
          publisherName: "PublishersName12"
        address: 
          poBoxNumber: "23451"
          buildingHouseNumber: "312"
          streetName: "StreetName12"
          cityName: "CityName12"
          stateProvince: "StateProvince12"
          postalCode: "12345"
        regions: 
          - region: "Asia"
