 #%RAML 1.0 NamedExample
value:
  publisher:
    publisherName: "PublishersName11"
  address: 
    poBoxNumber: "12345"
    buildingHouseNumber: "231"
    streetName: "StreetName11"
    cityName: "CityName11"
    stateProvince: "StateProvince11"
    postalCode: "11345"
  regions: 
    - region: "Africa"
    - region: "Europe"
